AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: stockalert

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    Handler: app.lambda_handler
    Runtime: python3.8

Parameters:
  KmsKey:
    Type: String

Resources:
  DiscordFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: discord
      Environment:
        Variables:
          KMS_KEY: !Ref KmsKey
  Sns:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Protocol: lambda
          Endpoint: !GetAtt DiscordFunction.Arn
  DebugSns:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Protocol: lambda
          Endpoint: !GetAtt DiscordFunction.Arn
  SnsPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref DiscordFunction
      Principal: sns.amazonaws.com
  StockAlertFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: stockalert
      Environment:
        Variables:
          NOTIFY_SNS_ARN: !Ref Sns
      Events:
        CloudWatchEvent:
          Type: Schedule
          Properties:
            Schedule: cron(*/10 * * * ? *)
