AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: stockalert

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

Parameters:
  SnsArn:
    Type: String
  KmsKey:
    Type: String
  DiscordWebhookUrl:
    Type: String

Resources:
  StockAlertFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: stockalert
      Handler: app.lambda_handler
      Runtime: python3.8
      Environment:
        Variables:
          NOTIFY_SNS_ARN: !Ref SnsArn
      Events:
        CloudWatchEvent:
          Type: Schedule
          Properties:
            # Every minute between 7AM and 10PM Eastern Time (UTC-5)
            Schedule: cron(* 12-3 * * ? *)
  Queue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: stockalert
  SnsToSqsSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: sqs
      Endpoint: !GetAtt Queue.Arn
      TopicArn: !Ref SnsArn
  DiscordFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: discord
      Handler: app.lambda_handler
      Runtime: python3.8
      Environment:
        Variables:
          KMS_KEY: !Ref KmsKey
          DISCORD_WEBHOOK_URL: !Ref DiscordWebhookUrl
      Events:
        SqsEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt Queue.Arn
            BatchSize: 10
Outputs:
  StockAlertFunction:
    Description: "StockAlertFunction ARN"
    Value: !GetAtt StockAlertFunction.Arn
  StockAlertFunctionIamRole:
    Description: "Implicit IAM Role created for StockAlertFunction"
    Value: !GetAtt StockAlertFunctionRole.Arn
  DiscordFunctionIamRole:
    Description: "Implicit IAM Role created for DiscordFunctionIamRole"
    Value: !GetAtt DiscordFunctionRole.Arn
