AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: stockalert

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  StockAlertFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: stockalert_function
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        CloudWatchEvent:
          Type: Schedule
          Properties:
            # Every minute between 7AM and 10PM Eastern Time (UTC-5)
            Schedule: cron(* 12-3 * * ? *)
        LocalInvokeApi:
          Type: Api
          Properties:
            Path: /invoke
            Method: GET

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  StockAlertFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt StockAlertFunction.Arn
  StockAlertFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt StockAlertFunctionRole.Arn
