name: Deploy

on: [push]

jobs:
  aws_sam:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@master

      - name: sam build
        uses: youyo/aws-sam-action/python3.8@master
        with:
          sam_command: build
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-west-2

      - name: sam deploy
        uses: youyo/aws-sam-action/python3.8@master
        with:
          sam_command: 'deploy --no-fail-on-empty-changeset --stack-name stockalert --s3-bucket stockalert-artifacts --parameter-overrides NotifySnsArn=arn:aws:sns:us-west-2:811555881555:stockalert --region us-west-2 --capabilities CAPABILITY_IAM'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}